global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'users-service'
    static_configs:
      - targets: ['users-service:8001']

  - job_name: 'product-catalog-service'
    static_configs:
      - targets: ['product-catalog-service:8002']

  - job_name: 'orders-service'
    static_configs:
      - targets: ['orders-service:8003']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']

  - job_name: 'notifications-service'
    static_configs:
      - targets: ['notifications-service:8080']
